version: '3'

services:
  postgresSQL:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: xsky
      POSTGRES_PASSWORD: xsky
      POSTGRES_DB: X-Sky
    volumes:
      - ./db-data/:/var/lib/postgresql/data/